default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: detect-private-key
    - id: mixed-line-ending
    - id: name-tests-test
      args: [--django]
    - id: pretty-format-json
  - repo: local
    hooks:
    # - id: django-tests
    #   name: django-tests
    #   entry: python app/manage.py test
    #   language: python
    #   types: [python]
    - id: isort
      name: isort
      entry: isort .
      language: python
      types: [python]
      pass_filenames: false
    - id: black
      name: black
      entry: black .
      language: python
      types: [python]
      pass_filenames: false
    - id: mypy
      name: mypy
      entry: mypy .
      language: python
      types: [python]
      pass_filenames: false
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      types: [python]
      pass_filenames: false
