default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: detect-private-key
    - id: mixed-line-ending
    - id: name-tests-test
      args: [--django]
    - id: pretty-format-json
  - repo: local
    hooks:
    - id: isort
      name: isort
      entry: isort .
      language: python
      files: python
    - id: black
      name: black
      entry: black .
      language: python
      files: python
    - id: mypy
      name: mypy
      entry: mypy .
      language: python
      files: python
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      files: python
