name: Build setup
description: Build all the necessary artifacts to run CI tests
runs:
  using: composite
  steps:
    - name: Set up Python 3.10.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.10
    - name: Setup poetry
      uses: snok/install-poetry@v1.3.3
      with:
        version: 1.4.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Set up cache
      id: cache-poetry
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ runner.os }}-${{ hashFiles(**/poetry.lock) }}

    - name: Install dependencies
      if: ${{ steps.cache-poetry.outputs.cache-hit != 'true' }}
      shell: bash
      run: poetry install --only dev --no-interactive --no-root
