name: CI

on: [push]

jobs:
  test_checks:
    name: Django tests and pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout repo
        uses: actions/checkout@v3
      # - name: Django Tests
      #   run: docker compose run --rm app sh -c "python app/manage.py test app/"
      - name: Build dependencies for pre-commit
        uses: ./.github/setup
      - name: Pre-commit checks
        uses: pre-commit/action@v3.0.0
