name: CI

on: [push]

jobs:
  test_lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Test
        run: docker compose run --rm --build app sh -c "python app/manage.py test"
      - name: Lint
        run: docker compose run --rm --build app sh -c "isort . && black . && flake8"
